---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - posts
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - pages
upload_dir: public/photos
public_path: "/photos"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: out
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
