import type { Exercise } from '../../types/kettlebell';

export const EXERCISES: Exercise[] = [
  // ============================================================
  // 1. BALLISTIC HINGE (Posterior Chain) — 9 exercises
  // ============================================================
  {
    id: 'two_hand_swing',
    name: 'Two-Hand Swing',
    nameEs: 'Swing a Dos Manos',
    description:
      'Ejercicio balístico fundamental que potencia la cadena posterior mediante una extensión explosiva de cadera.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'erectores espinales'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 1,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['heavy'],
    videoId: '1cVT3ee9mgU', // Kettlebell Kings - Two Hand Swing
    tips: 'Mantén los brazos como cuerdas, las caderas como bisagras. Aplasta la nuez de tierra entre tus talones.',
  },
  {
    id: 'one_hand_swing',
    name: 'One-Hand Swing',
    nameEs: 'Swing a Una Mano',
    description:
      'Versión unilateral del swing que exige mayor estabilización del core y transferencia de fuerza a un solo lado.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'hombros', 'antebrazos'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 2,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium', 'light'],
    videoId: '7HGWdth9SIo', // Kettlebell Kings - Single Arm Swing
    tips: 'El brazo libre se mueve como un péndulo opuesto. No tuerzas el torso; mantén hombros nivelados.',
  },
  {
    id: 'alternating_swing',
    name: 'Alternating Swing',
    nameEs: 'Swing Alternante',
    description:
      'Swing dinámico con cambio de mano en cada repetición, ideal para cadenas de alta intensidad.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'hombros', 'antebrazos'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 2,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium'],
    videoId: 'Lwzk5mxbN7Y', // Alternating Swing Demo
    tips: 'Cambia la mano en el punto más alto del swing. La entrega debe ser suave, sin perder el ritmo de cadera.',
  },
  {
    id: 'clean',
    name: 'Clean',
    nameEs: 'Clean de Pesa Rusa',
    description:
      'Movimiento balístico que lleva la pesa desde la posición de balanceo hasta el rack en un solo gesto explosivo.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['trapecios', 'bíceps', 'core'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 3,
    startingPosition: 'hang',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['medium'],
    videoId: 'km3f8_rpDdg', // Kettlebell Kings - Clean
    tips: 'La pesa debe aterrizar suavemente en el triángulo formado por antebrazo, pecho y bíceps. No tire de ella con el brazo.',
  },
  {
    id: 'snatch',
    name: 'Snatch',
    nameEs: 'Snatch de Pesa Rusa',
    description:
      'El zar de los ejercicios con pesa rusa: un movimiento explosivo de piso a overhead en una sola acción fluida.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales', 'hombros'],
    secondaryMuscles: ['core', 'trapecios'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 5,
    startingPosition: 'hang',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['light'],
    videoId: 'AHtr-W53KtI', // Kettlebell Kings - Snatch
    tips: 'Puncha a través del mango en la parte alta. El codo debe bloquearse con el brazo pegado a la oreja.',
  },
  {
    id: 'high_pull',
    name: 'High Pull',
    nameEs: 'Tirón Alto',
    description:
      'Tirón explosivo que conecta el swing con el snatch, fortaleciendo la fase de aceleración y el trapecio.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales', 'trapecios'],
    secondaryMuscles: ['core', 'deltoides'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 3,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium', 'light'],
    videoId: 'VIDCrY9RER8', // Kettlebell Kings High Pull
    tips: 'Lidera con el codo, no con la mano. La fuerza viene de la cadera, el brazo solo guía.',
  },
  {
    id: 'hiking_swing',
    name: 'Hiking Swing',
    nameEs: 'Swing en Posición de Hike',
    description:
      'Swing desde la posición de hike en el suelo, ideal para aprender el patrón de carga y la conexión con la gravedad.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'erectores espinales'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 1,
    startingPosition: 'floor',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['heavy'],
    videoId: 'TRUfIXjtYiI', // Pat Flynn Hike Drill
    tips: 'Tensa los dorsales antes de iniciar. Imagina que arrancas la pesa del suelo como si fuera un arco tensado.',
  },
  {
    id: 'double_swing',
    name: 'Double Swing',
    nameEs: 'Swing Doble',
    description:
      'Swing con dos pesas rusas simultáneas, duplicando la demanda de potencia y estabilización.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'erectores espinales', 'antebrazos'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 4,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['heavy'],
    videoId: 'BU-DIUnGnRE', // Rogue Fitness Double Swing
    tips: 'Mantén ambas pesas simétricas en todo el recorrido. Si una se adelanta, reduce el peso hasta dominar la técnica.',
  },
  {
    id: 'dead_stop_swing',
    name: 'Dead Stop Swing',
    nameEs: 'Swing con Parada',
    description:
      'Swing que inicia desde el suelo en cada repetición, eliminando el reflejo de estiramiento y exigiendo fuerza pura.',
    equipment: 'kettlebell',
    modality: 'ballistic',
    pattern: 'hinge',
    primaryMuscles: ['glúteos', 'isquiotibiales'],
    secondaryMuscles: ['core', 'erectores espinales'],
    bodyParts: ['posterior', 'legs', 'core'],
    complexity: 2,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [
      'hiking_swing',
      'dead_stop_swing',
      'floor_press',
      'deck_squat',
      'renegade_row',
      'pullover',
      'turkish_get_up',
      'man_maker',
    ],
    weightLevel: ['heavy'],
    videoId: 'zvN0Xu4bGyg', // Kettlebell Emma Dead Stop
    tips: 'Cada rep es un evento aislado. Reinicia la tensión desde cero: aprieta glúteos, bloquea el core, luego explota.',
  },

  // ============================================================
  // 2. SQUAT PATTERN (Knee Dominant) — 7 exercises
  // ============================================================
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    nameEs: 'Sentadilla Goblet',
    description:
      'Sentadilla frontal con la pesa sujetada al pecho, excelente para aprender la profundidad y la postura correcta.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['core', 'aductores'],
    bodyParts: ['legs', 'core'],
    complexity: 1,
    startingPosition: 'rack',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['heavy', 'medium'],
    videoId: 's64Ss68bABQ', // Perfect Goblet Squat
    tips: 'Sujeta la pesa por los cuernos y mantén los codos dentro de las rodillas. Baja hasta que los codos toquen los muslos.',
  },
  {
    id: 'double_front_squat',
    name: 'Double Front Squat',
    nameEs: 'Sentadilla Frontal Doble',
    description:
      'Sentadilla con dos pesas en posición de rack, máxima carga para piernas y core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['core', 'erectores espinales'],
    bodyParts: ['legs', 'core'],
    complexity: 4,
    startingPosition: 'rack',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['heavy'],
    videoId: 'yv1Nygxx7rk', // CrossFit Invictus Double Squat
    tips: 'Mantén los codos altos y el pecho orgulloso. Si las pesas se separan del cuerpo, estás perdiendo la postura.',
  },
  {
    id: 'rack_squat',
    name: 'Rack Squat',
    nameEs: 'Sentadilla en Rack a Una Mano',
    description:
      'Sentadilla unilateral en rack que desafía la estabilidad lateral y la fuerza del core de forma asimétrica.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['core', 'estabilizadores de cadera'],
    bodyParts: ['legs', 'core'],
    complexity: 3,
    startingPosition: 'rack',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['medium'],
    videoId: 'U-8AxRHCr3M', // Seriously Strong Rack Squat
    tips: 'La pesa descansa en el rack con puño neutro. Evita inclinarte hacia el lado cargado; mantén el torso centrado.',
  },
  {
    id: 'cossack_squat',
    name: 'Cossack Squat',
    nameEs: 'Sentadilla Cosaca',
    description:
      'Sentadilla lateral profunda que desarrolla movilidad de cadera, fuerza de aductores y control unilateral.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'aductores', 'glúteos'],
    secondaryMuscles: ['core', 'flexores de cadera'],
    bodyParts: ['legs', 'core'],
    complexity: 4,
    startingPosition: 'rack',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['medium', 'light'],
    videoId: 'J86g1YDBVZ4', // Jen Sinkler Cossack Squat
    tips: 'Mantén el talón de la pierna de trabajo pegado al suelo. La pierna extendida se flexiona solo lo que la movilidad permita.',
  },
  {
    id: 'deck_squat',
    name: 'Deck Squat',
    nameEs: 'Sentadilla al Suelo',
    description:
      'Sentadilla que desciende hasta sentarse y rodar hacia atrás, luego se recupera de pie. Desafío extremo de fuerza y movilidad.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos', 'core'],
    secondaryMuscles: ['isquiotibiales', 'erectores espinales'],
    bodyParts: ['legs', 'core'],
    complexity: 5,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [
      'hiking_swing',
      'dead_stop_swing',
      'floor_press',
      'deck_squat',
      'renegade_row',
      'pullover',
      'turkish_get_up',
      'man_maker',
    ],
    weightLevel: ['medium', 'light'],
    videoId: 't5DjwAd5q20', // Kettlebell Kings Deck Squat
    tips: 'Rueda suavemente hacia atrás manteniendo la pesa pegada al pecho. Impulsa con el metro para levantarte.',
  },
  {
    id: 'pistol_squat',
    name: 'Pistol Squat (Assisted)',
    nameEs: 'Sentadilla Pistol Asistida',
    description:
      'Sentadilla a una pierna con contrapeso de pesa rusa, desarrollando fuerza unilateral y equilibrio.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['core', 'isquiotibiales', 'estabilizadores'],
    bodyParts: ['legs', 'core'],
    complexity: 5,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['light', 'bodyweight'],
    videoId: '-U-TwEl411U', // REP Fitness Pistol Squat
    tips: 'Usa la pesa como contrapeso extendiéndola al frente. Baja con control, nunca te dejes caer.',
  },
  {
    id: 'tactical_lunge',
    name: 'Tactical Lunge',
    nameEs: 'Estocada Táctica',
    description:
      'Estocada hacia atrás con la pesa en rack, combinando fuerza unilateral con estabilidad del core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'squat',
    primaryMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['core', 'isquiotibiales'],
    bodyParts: ['legs', 'core'],
    complexity: 2,
    startingPosition: 'rack',
    endingPosition: 'rack',
    validNextExercises: [
      'strict_press',
      'push_press',
      'jerk',
      'see_saw_press',
      'bottoms_up_press',
      'sots_press',
      'goblet_squat',
      'double_front_squat',
      'rack_squat',
      'cossack_squat',
      'tactical_lunge',
      'thruster',
      'cluster',
      'bent_press',
    ],
    weightLevel: ['medium'],
    videoId: 'x006R5W29z8', // Kettlebell Tactical Lunge
    tips: 'El paso debe ser lo suficientemente largo para que la rodilla frontal no pase del pie. Mantén el torso erguido.',
  },

  // ============================================================
  // 3. PUSH PATTERN (Upper Body Anterior) — 7 exercises
  // ============================================================
  {
    id: 'strict_press',
    name: 'Strict Press',
    nameEs: 'Press Estricto de Hombros',
    description:
      'Press de hombros desde el rack sin impulso de piernas, puro esfuerzo de la cintura escapular.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps'],
    secondaryMuscles: ['core', 'trapecios'],
    bodyParts: ['push', 'core'],
    complexity: 2,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium'],
    videoId: 'Ay9W-movDuE', // Mark Wildman - Strict Press
    tips: 'Aprieta los glúteos y el core como si te fueran a empujar. El brazo debe quedar pegado a la oreja arriba.',
  },
  {
    id: 'push_press',
    name: 'Push Press',
    nameEs: 'Push Press',
    description:
      'Press de hombros con doble impulso de piernas que permite mover más peso que el press estricto.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps'],
    secondaryMuscles: ['cuádriceps', 'core'],
    bodyParts: ['push', 'core'],
    complexity: 3,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium', 'heavy'],
    videoId: 'CCqru4q9RK0', // Onnit - Push Press
    tips: 'Doble flexión de rodillas: una pequeña y una grande. Empuja con las piernas y remata con los brazos.',
  },
  {
    id: 'jerk',
    name: 'Jerk',
    nameEs: 'Jerk',
    description:
      'Técnica olímpica de envión donde las piernas hacen el trabajo pesado y los brazos solo estabilizan.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps'],
    secondaryMuscles: ['cuádriceps', 'core', 'trapecios'],
    bodyParts: ['push', 'core'],
    complexity: 5,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium', 'heavy'],
    videoId: 'JryhaLv9V2k', // StrongFirst - Jerk Under-drop
    tips: 'El split o la sentadilla deben ocurrir bajo la pesa, no después. Practica el timing con pesa ligera primero.',
  },
  {
    id: 'floor_press',
    name: 'Floor Press',
    nameEs: 'Press en Suelo',
    description:
      'Press de pecho acostado en el suelo que elimina el impulso de piernas y protege el hombro.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['pecho', 'tríceps'],
    secondaryMuscles: ['hombros', 'dorsales'],
    bodyParts: ['push', 'core'],
    complexity: 2,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [
      'hiking_swing',
      'dead_stop_swing',
      'floor_press',
      'deck_squat',
      'renegade_row',
      'pullover',
      'turkish_get_up',
      'man_maker',
    ],
    weightLevel: ['medium', 'heavy'],
    videoId: 'pNgpSubqYMQ', // Kettlebell Floor Press Demo
    tips: 'Los codos forman un ángulo de 45 grados respecto al torso, no los abras en exceso. Aprieta los omóplatos.',
  },
  {
    id: 'see_saw_press',
    name: 'See-Saw Press',
    nameEs: 'Press Alternante',
    description:
      'Press alternante donde una pesa sube mientras la otra baja, exigiendo control y ritmo continuo.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps'],
    secondaryMuscles: ['core', 'trapecios'],
    bodyParts: ['push', 'core'],
    complexity: 3,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium'],
    videoId: 'Y7IXTZKEpOY', // Chris Lopez See-Saw Press
    tips: 'Mantén un ritmo de metrónomo: arriba-abajo, arriba-abajo. El core trabaja doble para mantener la estabilidad.',
  },
  {
    id: 'bottoms_up_press',
    name: 'Bottoms-Up Press',
    nameEs: 'Press Invertido',
    description:
      'Press con la pesa invertida (base hacia arriba), el mejor ejercicio para fuerza de agarre y estabilidad del hombro.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps', 'antebrazos'],
    secondaryMuscles: ['core', 'estabilizadores del hombro'],
    bodyParts: ['push', 'core'],
    complexity: 4,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['light'],
    videoId: 'J5LEpIZSDS0', // Bottoms-up Press Technique
    tips: 'Aprieta el mango como si quisieras aplastarlo. Si la pesa se tumba, estás usando demasiado peso.',
  },
  {
    id: 'sots_press',
    name: 'Sots Press',
    nameEs: 'Press Sots',
    description:
      'Press de hombros desde la posición profunda de sentadilla, demanda movilidad torácica y fuerza extrema del core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros', 'tríceps'],
    secondaryMuscles: ['cuádriceps', 'core', 'movilidad torácica'],
    bodyParts: ['push', 'core'],
    complexity: 5,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['light'],
    videoId: 'ADeaZ9vENn8', // Kettlebell Kings Sots Press
    tips: 'No te levantes de la sentadilla al presionar. Mantén el pecho alto y la columna neutra en todo momento.',
  },

  // ============================================================
  // 4. PULL PATTERN (Upper Body Posterior) — 5 exercises
  // ============================================================
  {
    id: 'renegade_row',
    name: 'Renegade Row',
    nameEs: 'Remo Renegado',
    description:
      'Remo en posición de plancha con las pesas como base, combinando fuerza de espalda con estabilidad extrema del core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['dorsales', 'romboides'],
    secondaryMuscles: ['core', 'tríceps', 'pecho'],
    bodyParts: ['pull', 'core'],
    complexity: 4,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [
      'hiking_swing',
      'dead_stop_swing',
      'floor_press',
      'deck_squat',
      'renegade_row',
      'pullover',
      'turkish_get_up',
      'man_maker',
    ],
    weightLevel: ['medium'],
    videoId: 'qkgs2JOBkg4', // Renegade Row Demo
    tips: 'Cero rotación de cadera al remar. El cuerpo se mueve como una tabla, solo el brazo trabaja.',
  },
  {
    id: 'gorilla_row',
    name: 'Gorilla Row',
    nameEs: 'Remo Gorila',
    description:
      'Remo bilateral con dos pesas en posición de hinge, ideal para volumen de espalda sin fatigar el core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['dorsales', 'romboides'],
    secondaryMuscles: ['core', 'bíceps'],
    bodyParts: ['pull', 'core'],
    complexity: 2,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium', 'heavy'],
    videoId: 'ljzLtsz63YM', // Gorilla Row Demo
    tips: 'Mantén la espalda plana en hinge. Tira del codo hacia la cadera, no hacia el cielo.',
  },
  {
    id: 'single_arm_row',
    name: 'Single-Arm Row',
    nameEs: 'Remo a Una Mano',
    description:
      'Remo clásico a una mano en posición de staggered stance, fundamental para el desarrollo de la espalda.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['dorsales', 'romboides'],
    secondaryMuscles: ['bíceps', 'core'],
    bodyParts: ['pull', 'core'],
    complexity: 1,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium'],
    videoId: 'l5qelXL5nfs', // Single Arm Row Demo
    tips: 'Apoya la mano libre en el muslo o banco. Lleva el codo más allá de la línea del torso para máxima contracción.',
  },
  {
    id: 'batwing_row',
    name: 'Batwing Row',
    nameEs: 'Remo Batwing',
    description:
      'Remo isométrico con retención en la posición más alta, enfocado en romboides y corrección postural.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['romboides', 'trapecios medios'],
    secondaryMuscles: ['dorsales', 'bíceps'],
    bodyParts: ['pull', 'core'],
    complexity: 3,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [
      'two_hand_swing',
      'one_hand_swing',
      'alternating_swing',
      'clean',
      'snatch',
      'high_pull',
      'double_swing',
      'gorilla_row',
      'single_arm_row',
      'batwing_row',
      'pistol_squat',
    ],
    weightLevel: ['medium', 'heavy'],
    videoId: 'VzPRQWJb1ZA', // Batwing Row Tutorial
    tips: 'Sostén la posición alta 3-5 segundos por repetición. Aprieta los omóplatos como si sujetaras un lápiz entre ellos.',
  },
  {
    id: 'pullover',
    name: 'Kettlebell Pullover',
    nameEs: 'Pullover con Pesa Rusa',
    description:
      'Extensión de la pesa por detrás de la cabeza acostado, trabajando dorsales y pecho en el plano transversal.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['dorsales', 'pecho'],
    secondaryMuscles: ['tríceps', 'core'],
    bodyParts: ['pull', 'core'],
    complexity: 2,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [
      'hiking_swing',
      'dead_stop_swing',
      'floor_press',
      'deck_squat',
      'renegade_row',
      'pullover',
      'turkish_get_up',
      'man_maker',
    ],
    weightLevel: ['medium', 'light'],
    videoId: '96STTfPthqQ', // Kettlebell Pullover Demo
    tips: 'Mantén los codos ligeramente flexionados y aprieta los dorsales durante todo el recorrido. No arquee excesivamente la espalda baja.',
  },

  // ============================================================
  // 5. HYBRID / FULL BODY FLOWS — 6 exercises
  // ============================================================
  {
    id: 'turkish_get_up',
    name: 'Turkish Get-Up',
    nameEs: 'Levantamiento Turco (TGU)',
    description:
      'Secuencia completa de levantamiento desde el suelo hasta posición erguida con la pesa overhead, el test definitivo de movilidad y control.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['hombros', 'core', 'glúteos'],
    secondaryMuscles: ['cuádriceps', 'isquiotibiales', 'estabilizadores'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 3,
    startingPosition: 'floor',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium', 'light'],
    videoId: 'unaUWCyVnmQ', // Pavel Krotov TGU Breakdown
    tips: 'Muévete como si tuvieras un vaso de agua en el puño. Cada transición es una oportunidad para reiniciar la tensión.',
  },
  {
    id: 'thruster',
    name: 'Thruster',
    nameEs: 'Thruster con Pesa Rusa',
    description:
      'Combinación de sentadilla frontal y press de hombros en un solo movimiento continuo, máximo rendimiento metabólico.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['cuádriceps', 'hombros', 'glúteos'],
    secondaryMuscles: ['core', 'tríceps'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 3,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium'],
    videoId: '1gTmxXczDDk', // Kettlebell Thruster Demo
    tips: 'Usa el impulso de la subida de la sentadilla para lanzar la pesa. No separes las fases, conéctalas.',
  },
  {
    id: 'cluster',
    name: 'Cluster',
    nameEs: 'Cluster',
    description:
      'Complejo de clean + squat + jerk encadenado sin pausa, el ejercicio de mayor demanda neuromuscular del repertorio.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['cuádriceps', 'hombros', 'glúteos'],
    secondaryMuscles: ['core', 'tríceps', 'isquiotibiales'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 5,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium'],
    videoId: '-SQ4wOju3Gs', // Single Arm Cluster Demo
    tips: 'Cada transición debe ser fluida: clean → squat → jerk. No descanses entre fases, mantén la tensión.',
  },
  {
    id: 'windmill',
    name: 'Windmill',
    nameEs: 'Molino',
    description:
      'Flexión lateral con la pesa overhead, combinando movilidad de cadera, fuerza de hombro y control del core.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['oblicuos', 'hombros', 'core'],
    secondaryMuscles: ['isquiotibiales', 'glúteos'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 3,
    startingPosition: 'overhead',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['light'],
    videoId: 'ITSmgn_BQgY', // Onnit Windmill Tutorial
    tips: 'Empuja la pesa hacia el cielo mientras bajas. La mirada siempre en la pesa. Baja solo hasta donde mantengas la pierna recta.',
  },
  {
    id: 'bent_press',
    name: 'Bent Press',
    nameEs: 'Bent Press',
    description:
      'Prensa lateral histórica donde el cuerpo baja bajo la pesa fija, desarrollando fuerza y movilidad extrema.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['hombros', 'oblicuos', 'tríceps'],
    secondaryMuscles: ['core', 'glúteos', 'cuádriceps'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 5,
    startingPosition: 'rack',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['light', 'medium'],
    videoId: 'LmBQ7H95ejU', // Dave Whitley Bent Press
    tips: 'La pesa no sube, tú bajas. Inclina el torso lateralmente mientras el brazo se extiende. Es un press, no un jerk.',
  },
  {
    id: 'man_maker',
    name: 'Man Maker',
    nameEs: 'Man Maker',
    description:
      'Complejo brutal de burpee + remo + clean + press que trabaja todo el cuerpo en una sola secuencia.',
    equipment: 'kettlebell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['cuádriceps', 'dorsales', 'hombros', 'pecho'],
    secondaryMuscles: ['core', 'glúteos', 'tríceps'],
    bodyParts: ['full_body', 'core', 'legs', 'posterior'],
    complexity: 5,
    startingPosition: 'floor',
    endingPosition: 'overhead',
    validNextExercises: ['windmill'],
    weightLevel: ['medium'],
    videoId: 'P4BIVAgJbZY', //
    tips: 'Mantén la intensidad pero nunca sacrifiques la técnica por velocidad. Respira: baja → remo → clean → press.',
  },

  // ============================================================
  // 6. DUMBBELL SUPPLEMENTATION — 6 exercises
  // ============================================================
  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    nameEs: 'Press de Banca con Mancuernas',
    description:
      'Press de pecho en banco plano con mancuernas, permitiendo mayor rango de movimiento que la barra.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['pecho', 'tríceps'],
    secondaryMuscles: ['hombros'],
    bodyParts: ['push'],
    complexity: 1,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [],
    weightLevel: ['medium', 'heavy'],
    videoId: '1V3vpcaxRYQ', // DB Bench Press Demo
    tips: 'Baja hasta sentir un estiramiento completo en el pecho. Los codos a 45 grados, no en T.',
  },
  {
    id: 'db_flyes',
    name: 'Dumbbell Flyes',
    nameEs: 'Aperturas con Mancuernas',
    description:
      'Aperturas en banco plano que aíslan el pectoral mayor con un énfasis en el estiramiento bajo carga.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['pecho'],
    secondaryMuscles: ['hombros', 'bíceps'],
    bodyParts: ['push'],
    complexity: 2,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [],
    weightLevel: ['light', 'medium'],
    videoId: 'Nhvz9EzdJ4U', // DB Flyes Demo
    tips: 'Mantén una ligera flexión de codos constante. Imagina que abrazas un barril gigante.',
  },
  {
    id: 'db_calf_raise',
    name: 'Dumbbell Calf Raise',
    nameEs: 'Elevación de Pantorrillas con Mancuerna',
    description:
      'Elevación de talones de pie con mancuerna en mano, fortaleciendo el tríceps sural.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'hybrid',
    primaryMuscles: ['pantorrillas'],
    secondaryMuscles: ['tibiales'],
    bodyParts: ['legs'],
    complexity: 1,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [],
    weightLevel: ['heavy', 'medium'],
    videoId: 'E1mG5L9rpFc', // DB Calf Raise Demo
    tips: 'Sube hasta la punta de los dedos con control, pausa arriba un segundo. No rebotes.',
  },
  {
    id: 'db_incline_curl',
    name: 'Dumbbell Incline Curl',
    nameEs: 'Curl Inclinado con Mancuernas',
    description:
      'Curl de bíceps en banco inclinado que maximiza el estiramiento del bíceps y elimina el impulso.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'pull',
    primaryMuscles: ['bíceps'],
    secondaryMuscles: ['antebrazos'],
    bodyParts: ['pull'],
    complexity: 1,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [],
    weightLevel: ['light', 'medium'],
    videoId: 'XVQBeug_9LU', // Incline Curl Tutorial
    tips: 'Los brazos cuelgan verticalmente desde el banco. Rota las muñecas en la subida y controla la bajada.',
  },
  {
    id: 'db_skullcrusher',
    name: 'Dumbbell Skull Crusher',
    nameEs: 'Extensión de Tríceps con Mancuernas',
    description:
      'Extensión de tríceps acostado con mancuernas, aislamiento efectivo para la cabeza larga del tríceps.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['tríceps'],
    secondaryMuscles: ['codos'],
    bodyParts: ['push'],
    complexity: 1,
    startingPosition: 'floor',
    endingPosition: 'floor',
    validNextExercises: [],
    weightLevel: ['light', 'medium'],
    videoId: '1BDGIcMTSXc', // DB Skull Crusher Technique
    tips: 'Los codos apuntan al cielo y permanecen fijos. Solo el antebrazo se mueve. Controla la bajada hasta la frente.',
  },
  {
    id: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    nameEs: 'Elevación Lateral con Mancuernas',
    description:
      'Elevación lateral de los brazos para aislar el deltoides medio, clave para hombros saludables.',
    equipment: 'dumbbell',
    modality: 'grind',
    pattern: 'push',
    primaryMuscles: ['hombros (deltoide medio)'],
    secondaryMuscles: ['trapecios'],
    bodyParts: ['push'],
    complexity: 1,
    startingPosition: 'hang',
    endingPosition: 'hang',
    validNextExercises: [],
    weightLevel: ['light'],
    videoId: 'UFcaodmbXd8', // Lateral Raise Tutorial
    tips: 'Inclínate ligeramente hacia adelante y lidera con los codos, no con las manos. Pesa ligera, forma perfecta.',
  },
];

export const EXERCISE_MAP: Record<string, Exercise> = EXERCISES.reduce<
  Record<string, Exercise>
>((map, e) => {
  map[e.id] = e;
  return map;
}, {});
